### ISSUE TITLE
Implement Document Query Builder

### ISSUE THREAD

**Issue by fmatthies** [Onto-Med/top-frontend#254]
- similar to `pages/QueryBuilder` there should be a `DocumentQueryBuilder`
- the `buildQuery` `q-btn` in `pages/Editor` could then forward to the former if it's a `Concept Repository`?

**Comment by ChristophB** [comment]
I'll try to combine both query builders into one page, where the user can select whether he wants to build a document or phenotype query. Depending on the selection, an appropriate form should get displayed. I think we can use most of the `QueryBuilder` page for both cases and we can extract the document and phenotype related stuff into separate components.

**Comment by ChristophB** [comment]
Unified query builders.

There is now a new component `EntityDisplay` that is used to show the selected concept for concept queries:


![Image](https://github.com/Onto-Med/top-frontend/assets/1651973/14186300-ede4-49f3-b0d5-878c7e145419)
