### ISSUE TITLE
Language Check

### ISSUE THREAD

**Issue by fmatthies** [Onto-Med/top-frontend#277]
Right now one can start a concept query in either language, even if the repository concepts don't feature a language entry in question. We could and should catch/handle this in `top-document-query` (and throw an error) if expressions can't be resolved because there is no such language entry.
But it might also be more user-friendly when there is a check in the frontend before starting a query if the language specified for the query is present in any of the terms. Is this feasible @ChristophB?

**Comment by ChristophB** [comment]
I think this is something that can easily be checked by the backend.

What should happen if a German query contains concepts where some have German content and other don't?

**Comment by fmatthies** [comment]
> What should happen if a German query contains concepts where some have German content and other don't?
Good question. Maybe those should be discarded?
Or we could implement yet another query option that governs whether the query language is

- restrictive (concepts that don't have a corresponding language entry are discarded)
- lenient (take the entry for the first and probably default language)

**Comment by fmatthies** [comment]
Current favored idea is:

- every query needs a language or default something like `all languages`
- if a specific language is selected, only concepts will be included that have a corresponding language entry
