### ISSUE TITLE
investigate FHIR dashboard

### ISSUE THREAD

**Issue by KonradHoeffner** [Onto-Med/top-frontend#302]
- INTERPOLAR Dashboard should be a tool for pharmacists to calculate and list patient medication risks
-  investigate tools to build and display FHIR resources like Questionnaire and QuestionnaireResponse.
- [x] Consider the possibility of exporting query results in the TOP-Framework as standardized FHIR resources, possibly integrating these tools in JavaScript. 

## Investigate

* [x] https://lhncbc.github.io/lforms/
* [x] https://lhcformbuilder.nlm.nih.gov/
* [x] https://confluence.hl7.org/plugins/servlet/mobile?contentId=66940123#content/view/66940123
* [x] https://confluence.hl7.org/display/FHIR/Open+Source+Implementations

**Comment by KonradHoeffner** [comment]
## LForms

**Comment by KonradHoeffner** [comment]
## Questionnaire and QuestionnaireResponse

See <https://www.hl7.org/fhir/questionnaire.html> and <https://www.hl7.org/fhir/questionnaireresponse.html>.
Questionnaire is a "sructured set of questions and their answers" intended for *data input*.
A QuestionnaireResponse is a filled out questionnaire.
The primary focus of this issue is the QuestionnaireResponse because we want to convert the ResultSet to a QuestionnaireResponse in order to use FHIR QuestionnaireResponse visualization tools.
However as a secondary benefit we could also use a Questionnaire to allow users to make changes and feed the result back into the FHIR server.
However this may be difficult to implement.

**Comment by KonradHoeffner** [comment]
## AG Grid Community Edition

In contrast to the other tools, [AG Grid](https://www.ag-grid.com/javascript-data-grid/licensing/) is not a FHIR tool but instead a pure JavaScript data table visualization tool, see [an example](https://www.ag-grid.com/example/).
While it does not support things like values with units by default, it does have a variety of filter functions, for example for sets including or excluding certain items, string containment and numerical comparisons (e.g. > or < a given x).

**Comment by KonradHoeffner** [comment]
## NLM Form Builder

Focus is on creating new Questionnaires, does not seem suitable for our purpose.

**Comment by KonradHoeffner** [comment]
## Conclusion

None of the investigated libraries and tools seem appropriate for a useful visualization.
Thus I recommend visualizing the ResultSet directly using AG Grid Community Edition.

**Comment by ChristophB** [comment]
AG Grid was introduced in 998953029a0a6ec90ae022b5339ca2ec0c3e0066.
