### ISSUE TITLE
TableWithActions overflows

### ISSUE THREAD

**Issue by fmatthies** [Onto-Med/top-frontend#313]
When restricting the height of the `q-card` (that contains the `table-with-actions`) to the viewport, the table goes outside the former borders. (If no restriction is placed on the `q-card`, it extends beyond the viewport and one has to scroll down (table header and page title aren't visible anymore)
Probably wasn't a problem when `table-with-actions` was solely used for Repositories and Organizations as there weren't that many to display.
![overflow_twa](https://github.com/Onto-Med/top-frontend/assets/4722688/954f2121-d97c-404f-8a5e-04b38e6fab9d)
![overflow_twa_card-ext](https://github.com/Onto-Med/top-frontend/assets/4722688/6cd03e20-b1be-4ce1-b013-17234cfcaea5)

**Comment by ChristophB** [comment]
Should be fixed now:

![image](https://github.com/Onto-Med/top-frontend/assets/1651973/9c749ae3-2c70-4ce2-90e7-0afe4210c0f0)

**Comment by fmatthies** [comment]
Thanks; looks good!
I still have to scroll a little bit (the `q-card` goes beyond the viewport).

![overflow_twa_card-ext2](https://github.com/Onto-Med/top-frontend/assets/4722688/8a2f735b-f55c-4441-a2b3-c1df64b64e52)

**Comment by ChristophB** [comment]
Yeah, this depends on the screen size. The header has a fixed height of 58px and the table is set to 72vh, which is relative to screen size.
