### ISSUE TITLE
Initialise concept pipeline

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-frontend#332]
The TOP framework can be connected to an instance of https://github.com/Onto-Med/concept-graphs. The backend already supports initialisation of a concept generation pipeline, but there is no way to do this from the frontend.

- [x] add necessary GUI elements to start the concept pipeline(s)
- [x] limit access to new GUI elements to admins

## Open Questions

There are multiple endpoints defined in the TOP API that are related to concept graph and cluster generation. To me it looks like at least two of them must be called sequentially. (i.e.: `startConceptGraphPipelineWithoutUpload` -> *wait some time\~* -> `createConceptClusterForProcessId`) This is a bit inconvenient and we need to find a way to simplify this process.

Also, a process ID must be given to initialising the concept graph pipeline. I picked 'top-framework' as ID for now.

**Comment by ChristophB** [comment]
I rebased the branch on `master` and removed duplicated commits.

**Comment by ChristophB** [comment]
Started working on the GUI elements. As we want to focus on `startConceptGraphPipelineWithoutUpload`, a button and a confirmation dialogue should be sufficient.

**Comment by ChristophB** [comment]
We could wait for the pipeline create promise to finish and start `createConceptClusterForProcessId` afterwards but this could lead to a gateway timeout exception depending on the corpus size and the web server configuration.

**Comment by fmatthies** [comment]
To add/clarify:
```
startConceptGraphPipelineWithoutUpload(
      String process,
      List<String> include,
      String lang,
      Boolean skipPresent,
      Boolean returnStatistics
)
```
`process`: this is intended to be the name of the corpus  
`skipPresent`: if true, all steps for a given corpus that were already completed will be skipped (could happen if the graph creation process was terminated prematurely at one of the four sequential steps)  
`returnStatistics`: if false, the creation process will run in the background (i.e. the python process) and the backend will return a response immediately this would circumvent timeout exceptions

**Comment by fmatthies** [comment]
I just realized that I totally forgot that I already implemented endpoints for checking the status of a process (in the `concept-graphs-api` as well as in the `ConceptGraphsRepository`, but didn't add an endpoint in the `top-api`:
```
  public enum API_STATUS {
    SELF("/status"),
    DOCUMENT_SERVER("/status/document-server");

    private String endpoint;

    API_STATUS(String endpoint) {
      this.setEndpoint(endpoint);
    }

    public String getEndpoint() {
      return endpoint;
    }

    public void setEndpoint(String endpoint) {
      this.endpoint = endpoint;
    }
  }
```
I imagined that to be the method to periodically check from the frontend whether the process started is already finished/at what point in the process it is.

**Comment by fmatthies** [comment]
if the status endpoint from concept-graphs-api is called (a process id is given by query argument) , it returns a status response:
```
    STARTED = "started"
    RUNNING = "running"
    FINISHED = "finished"
    ABORTED = "aborted"
    NOT_PRESENT = "not present"
```

**Comment by ChristophB** [comment]
After thinking more about the pipeline and how the user interacts with it, I got the feeling that it would be better if the backend could handle all the pipeline stuff at once. What I mean is: Currently the user starts the concept graph pipeline (A), waits for it to finish and starts the neo4j pipeline (B). B should start automatically. This extra user interaction adds no value.

Of course, we could implement some kind of automatic process in the frontend that checks if A has finished and starts B, but this adds complexity and only applies to the frontend - other tools will need to implement this step as well. It also feels more natural to have a REST endpoint to start the "pipeline" (A + B).

Would it be possible to merge [startConceptGraphPipelineWithoutUpload](https://onto-med.github.io/top-api/#/conceptgraphs/startConceptGraphPipelineWithoutUpload) and [createConceptClustersForProcessId](https://onto-med.github.io/top-api/#/conceptcluster/createConceptClustersForProcessId)? I am also not sure what `graphIds` are supposed to be requested with the latter.

BTW, `ConceptClusterService::createSpecificGraphsInNeo4j` could be done by JobRunr.

**Comment by ChristophB** [comment]
We should limit the pipeline to admins.

**Comment by fmatthies** [comment]
The reason why there are two methods is mainly because the `concept-graph` creation runs on a different server (with its respective REST endpoint) and the `concept-cluster` creation runs/and is implemented solely in the `backend`. There is certainly no need right now to keep them being called separately (and we could implement a method that starts both in a serialized fashion). But I wouldn't remove them altogether.

**Comment by fmatthies** [comment]
The `workflow` in its current form is as follows:  

1. The python `concept-graphs-api` runs a process where it takes some configuration files (how is the `text data` processed, how are the `embeddings` created and `clustered`, and how are the phrases from the text data `connected in a graph`) - these four steps can be repeated individually if the results are not to ones liking.
2. The backend `concept-cluster` creation is then run on these graphs to transfer them to the `Neo4j DB`

right now, (1) should be/and is run with some default configuration (but later on there should be a possibility to configure this). (2) has the feature to omit certain graphs (if they are non-informative -> e.g. some graphs are created that capture solely artifacts), this is done by the `graphIds`  
That's another reason why there are two separate methods, to allow for a validation step or some such before the entries in the Neo4j DB are created.

**Comment by ChristophB** [comment]
I'd like to postpone this topic until the next release. The implementation seems to be more complicated than I first thought.

I will create a release later today and try to come up with a mockup for the pipeline interface.

**Comment by ChristophB** [comment]
For the following mockup, it is required that multiple document sources can be connected to the framework (I think there was an issue that prevents using other Elasticsearch servers than the default one).

![pipeline-mockup](https://github.com/Onto-Med/top-frontend/assets/1651973/138b9d5f-06ee-43fa-8187-2f5b45ccf673)

**Comment by fmatthies** [comment]
That looks really good; thanks!
