### ISSUE TITLE
Speed up ESLint

### ISSUE THREAD

**Issue by KonradHoeffner** [Onto-Med/top-frontend#337]
On an Intel Core i9-12900k, `yarn lint` takes 28 seconds, which is more time than it takes to compile a Rust release build with 294 dependencies on that machine.
Can we somehow speed this up?

**Comment by ChristophB** [comment]
We could use `yarn lint --cache`, this will create a `.eslintcache` file and future calls to eslint will only process changed files.

**Comment by KonradHoeffner** [comment]
Sounds great!

**Comment by ChristophB** [comment]
I think easiest way is to add `.eslintcache` to `.gitignore` and update the lint entry in `package.json`.

**Comment by ChristophB** [comment]
Need to update the quasar configs as well, as they do not use the ESLint cache feature and delete `.eslintcache` automatically.
