### ISSUE TITLE
Fix broken pagination after new document related changes

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-frontend#345]
Reported by @fmatthies:

Pagination seems to be broken. It is not possible to switch to the next page, because the page parameter is set to undefined.

**Comment by fmatthies** [comment]
> wenn ich in `TableWithActions` unter `:model-value="page?.number || 0"` das `|| 0` entferne, wird `onPageSelect` nicht mehr zweimal aufgerufen, aber die Seite wird trotzdem nicht gewechselt, weil der `page` Wert dann zwar richtig ist und auch zusammen mit `filter.value` `emit`ed wird, aber in der `DocumentSearchForm` dann in `@request="reloadDocuments($event).catch((e: Error) => renderError(e))"` das `$event` nicht richtig aufgelöst wird (?) und nur der `filter.value` an `reloadDocuments` weitergegeben wird.
Wenn ich einfach nur `@request="reloadDocuments"` lasse, funktioniert alles.

**Comment by ChristophB** [comment]
Fixed in 1d9e2d483ffee2140fc97475a4adaf8a18357edb
